### ISSUE TITLE
Implement close functionality on mac (as a temporary bug fix, app fully quits when clicking the x).

### ISSUE THREAD

**Issue by danielfebrero** [BonBon-exchange/bonbon-web-browser#215]

**Comment by dcallus** [comment]
I can reproduce:

MacBook Pro Retina 2015: Big Sur 11.4
BonBon Browser 0.30.0 for macOS.

1. Open Browser
2. Close Browser with the x
3. BonBon is still running on navbar as expected
4. Reopen BonBon
5. White screen

Can be fixed with either Cmd + Q (full exit of the app) OR by adding a new board.

**Comment by danielfebrero** [comment]
Thank you for this. I should have an active developer on macOS soon.

> I'm assuming CNR = cannot reproduce
Yes correct

**Comment by dcallus** [comment]
When running in dev mode I get the following error when replicating this bug.

Error: Given BrowserView is not attached to the window
at IpcMainImpl.<anonymous> (/Users/---/Repos/bonbon-web-browser/src/main/ipcMainEvents.ts:94:22)
at IpcMainImpl.emit (node:events:526:28)
at IpcMainImpl.emit (node:domain:475:12)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
at EventEmitter.emit (node:events:526:28)
at EventEmitter.emit (node:domain:475:12)

**Comment by danielfebrero** [comment]
@dcallus 

The easiest way to fix it is to just quit the app on macOS when closing the window. It happens here: https://github.com/BonBon-exchange/bonbon-web-browser/blob/main/src/main/appEvents.ts#L49

The best way to fix it is to see why the BrowserView is not attached. Is it null? 

Can we look at it together?

**Comment by dcallus** [comment]
Yeah. I think it's definitely best to try and stick to the mac way of doing things. We can try and work on it together at some point on the weekend. Send me a telegram

**Comment by danielfebrero** [comment]
We isolated the main source of the problems.
ipcMainEvents views and freeViews should be reset on all windows closed.

**Comment by dcallus** [comment]
temporary fix added (app now quits on close). See PR #349

**Comment by danielfebrero** [comment]
We will create a new issue for the alternative close on mac.
