### ISSUE TITLE
UI bug: Max window should have a different icon.

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-web-browser#309]
## Expected Behavior
When you maximise a window with the square icon it should change to two squares (windows minimise icon).

## Current Behavior
When you maximise a window the maximise icon is still present.

## Steps to Reproduce
1. Maximise a window
2. Observe the icon has not changed.

N/A

**Comment by danielfebrero** [comment]
I cannot find the windows unmaximize icon on internet :(

**Comment by dcallus** [comment]
> I cannot find the windows unmaximize icon on internet :(

Me neither, I looked for quite a while. Will probably have to make a local svg, I don't mind doing this if you think it's the best solution.

**Comment by danielfebrero** [comment]
I found something by inspecting Visual Suidio Code with dev tools.
