### ISSUE TITLE
The X in the left bar to close webpage is innacurate at least on some macOS (see video)

### ISSUE THREAD

**Issue by danielfebrero** [BonBon-exchange/bonbon-web-browser#315]
https://user-images.githubusercontent.com/20900798/182143309-e8f8892e-24d2-46b5-a615-4e7edf1053fb.mp4

**Comment by dcallus** [comment]
spent some time on this and can't figure it out for the life of me. When you move the mouse to the right (out of the bounds) it disappears, when you move the mouse up it's fine. I almost got it working by extending certain element's width but it caused some weird glitches. Probably not a huge priority right now, it works well enough.

**Comment by danielfebrero** [comment]
Ok I mark this as low priority. Thanks for investigating.

**Comment by danielfebrero** [comment]
I believe v1-alpha fix this issue. I close it.
