### ISSUE TITLE
Remove white space around BrowserView on macOS

### ISSUE THREAD

**Issue by danielfebrero** [BonBon-exchange/bonbon-web-browser#350]

**Comment by dcallus** [comment]
is definitely not a css issue as far as I can see.

Any idea where to look @danielfebrero ? I had a look yesterday in Browser.tsx and couldn't get anything working.

**Comment by danielfebrero** [comment]
In fact I was refering to this file: https://github.com/BonBon-exchange/bonbon-web-browser/blob/main/src/main/browser.ts
and to look at the setBrowserViewBounds function, that may need a condition like:

`if (process.platform === 'darwin')`
