### ISSUE TITLE
No windows open on board displays as '?'

### ISSUE THREAD

**Issue by dcallus** [BonBon-exchange/bonbon-web-browser#353]
## Expected Behavior
When no windows are open on a board. There should be a (0) after the board name.

## Current Behavior
There is a (?) instead of a 0.

## Steps to Reproduce
1. Delete all windows from a board
2. See Question mark in board title.

N/A

**Comment by dcallus** [comment]
@danielfebrero just realised this is not a bug as the '?' is a chosen string. I assumed it was some null value.

Is there any reason why we have chosen a '?' over a '0' for the display?

**Comment by danielfebrero** [comment]
No reason anymore for this "?", it can be replaced by a 0.
