### ISSUE TITLE
Visual bug when renaming a Collection

### ISSUE THREAD

**Issue by danielfebrero** [BonBon-exchange/bonbon-web-browser#395]
## Current Behavior
![image](https://user-images.githubusercontent.com/20900798/184479202-569308f6-9916-412d-a95f-c1180482e685.png)

## Steps to Reproduce

1. Rename a tabulation

**Comment by dcallus** [comment]
Hmmm, I put this issue in already but it doesn't seem to be in the system. Strange. Worth noting that part of the issue is that you need to press Enter for it to finish the name change, otherwise it's stuck on editing mode. You should be able to click off the tab for it to complete also.

**Comment by danielfebrero** [comment]
> Hmmm, I put this issue in already but it doesn't seem to be in the system. Strange. Worth noting that part of the issue is that you need to press Enter for it to finish the name change, otherwise it's stuck on editing mode. You should be able to click off the tab for it to complete also.

No in fact the issue about Enter for exiting renaming has been fixed by me already!
