### ISSUE TITLE
is project stalled?

### ISSUE THREAD

**Issue by hcarrega** [BonBon-exchange/bonbon-web-browser#469]
## Summary
nothing new and telegram chat its silent

**Comment by sunk818** [comment]
Is there something you think is missing that you can contribute? maybe the developer has other priorities right now. I'm not under the impression there's any expectation of code contribution at all nor even at an expected steady pace.

**Comment by danielfebrero** [comment]
Correct, the project is not maintained anymore. Thank you for your interest!

**Comment by danielfebrero** [comment]
@sunk818 @hcarrega https://github.com/BonBon-exchange/bonbon-web-browser/discussions/479

project is wake up
