### ISSUE TITLE
Have the browser NOT maximize the window when opening a new tab. Insanely annoying on e.g. ultrawide monitor. Cheers.

### ISSUE THREAD

**Issue by joyzer** [BonBon-exchange/bonbon-web-browser#71]

**Comment by danielfebrero** [comment]
Thanks for the submition @joyzer, I will fix this asap.

**Comment by joyzer** [comment]
> Thanks for the submition @joyzer, I will fix this asap.

I just noticed that the same "problem" is for both new board as well as new tab. Just FYI.

**Comment by joyzer** [comment]
This is now happening again :(

**Comment by joyzer** [comment]
@danielfebrero 
This is now happening again :(

**Comment by danielfebrero** [comment]
@joyzer Oh really? No problem I will submit a fix and make a build this weekend.
Is it fine if at first opening, it maximize the window? It has been requested by some users. 
I will make sure it doesn't maximize at each new tab.
