### ISSUE TITLE
Translate app in Spanish, Catalan, Dutch and Polish

### ISSUE THREAD

**Issue by danielfebrero** [BonBon-exchange/bonbon-web-browser#97]

**Comment by 0xCUB3** [comment]
Here's the polish translation:
[Polish.zip](https://github.com/BonBon-exchange/bonbon-web-browser/files/9084719/Polish.zip)

**Comment by danielfebrero** [comment]
[nl.zip](https://github.com/BonBon-exchange/bonbon-web-browser/files/9085174/nl.zip)
